# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '15.0'
use_frameworks!
target 'Chicken Jump Quest' do
	project 'Chicken Jump Quest.xcodeproj'
	pod 'Google-Mobile-Ads-SDK', '~> 11.3.0'
	pod 'GoogleUserMessagingPlatform', '~> 2.0.0'
end
